FROM node:20-alpine    
           # apline -> linux server
           # node:20 -> node version 20

WORKDIR /app

COPY ./package.json /app  
COPY ./package-lock.json /app

RUN npm install


# copy all files to the container
COPY . /app


# COPY ./server.js .

CMD ["node", "server.js"]


# for run 
# docker build -t img_name 

# for made cantainer

# docker run  img_name


# port mapping
#  docker run -p 3000:3000 express 

